import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { apiStatus } from './api/services'

export default function Home() {

  const [status, setStatus] = useState();

  useEffect(() => {
    apiStatus().then((res) => {
      console.log(res.data.alive)
      setStatus(res.data.alive);
    }).catch((error) => {
      console.log(error);
    })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>2NAT - App Masters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Doação de computadores</h1>
        <div className={styles.description}>
          { status ? <p>API online</p>
                   : <p>API offline</p> }  
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
